#! /usr/bin/node

function init(args) {
    try {
        const users = csw.fs.read("/etc/passwd")
    
        if (args[0] == undefined) {
            args[0] = "root"
        }
        const user = args[0]

        // make sure user exists
        if (users[user] !== undefined) {
            if (users[user].password == undefined) {
                throw new Error(`User ${ user } does not have a password, login denied.`)
                return
            }
        } else {
            std.out = `User ${ user } does not exist.`
            return
        }

        const passwd = parent.changeUser(user)

        if (!passwd) {
            throw new Error("Sorry")
        }


    } catch(e) {
        throw new Error(e)
    }
}