#! /usr/bin/node

// message between processes

function init() {
    if (window.pcsMsg == undefined) {
        const pcsMsg = {messages: {}}
        window.pcsMsg = pcsMsg

        pcsMsg.getMessages = function (PID) {
            if (pcsMsg.messages[PID] == undefined) {
                pcsMsg.messages[PID] = []
            }
            return pcsMsg.messages[PID]
        }

        pcsMsg.sendMessage = function (originPID, targetPID, content) {
            if (pcsMsg.messages[PID] == undefined) {
                pcsMsg.messages[PID] = []
            }

            pcsMsg.messages[PID].push({
                origin: originPID,
                content: content
            })
        }
    }

    return window.pcsMsg
}