#! /usr/bin/node

function init() {
    const system = csw.permissions.elevate()

    const disk = JSON.stringify(system.fs)

    const byteSize = str => new Blob([str]).size;

    let diskSize = byteSize(disk)

    let unit = 1

    while (diskSize > 1024) {
        unit++
        diskSize /= 1024
    }

    let formatted = String(Math.round(diskSize))
    switch (unit) {
        case 1:
            formatted += "Bytes"
            break;
        case 2:
            formatted += "KiB"
            break;
        case 3:
            formatted += "MiB"
            break;
        case 4:
            formatted += "GiB"
            break;
        case 5:
            formatted += "TiB"
            break;
    }

    console.post(formatted)
}