#! /usr/bin/node

async function init(args) {
    const config = await call.read("/etc/pgext.json")

    if (parent.name == "/bin/aquila.js") {
        // CLI mode

        switch (args[0]) {
            case "mode":
                config.mode = args[1]
                break;
            default:
                std.out += "Options are as follows:\n- mode\n"
        }

        system.stopProcess(PID)
        return
    }

    // Service mode (background process)

    if (config == undefined) {
        const cfg = {}
        cfg.mode = "processes"

        call.write("/etc/pgext.json", cfg)
    }
}

async function frame() {
    const config = await call.read("/etc/pgext.json");

    let ending

    switch(config.mode) {
        case "processes":
            const processesList = await call.readdir("/proc");
            ending = " (" + processesList.length + " tasks)"
            break;
    }

    const targetTitle = await call.gethostname() + ending;

    if (document.title !== targetTitle) {
        document.title = targetTitle;
    };
}