#! /usr/bin/node

async function init() {

    call.shout("skyinit")

    const config = {
        main: await call.read("/etc/skylight/main.json")
    }

    const subsystems = config.main.subsystems

    for (const i in subsystems) {
        await call.exec(subsystems[i], [], true);
    }
}

function frame() {

}