#! /usr/bin/node

async function init() {
    std.out = "Not working at the moment, sorry"
    return
    async function walk(process, prefix, maxDepth, depth) {
        const inf = {
            name: await call.read("/proc/" + process + "/exe"),
            children: ""
        }
        const contents = process.children
        console.debug(process)
        contents.sort()

        for (const i in contents) {
            const procs = proc[contents[i]]
            console.debug(contents[i])
            console.debug(proc)
            const parts = i == contents.length - 1 ? ["└── ", "    "] : ["├── ", "│   "];

            std.out += `${prefix}${parts[0]}${procs.name}\n`;
            processCount += 1;
            await walk(procs, `${prefix}${parts[1]}`, maxDepth, depth + 1);
        }
    }

    let processCount = 0

    std.out = proc[1].name + "\n"
    await walk(0, "", Infinity, 0)
}