#! /usr/bin/node


function compile(code, safe) {
	// code gets provided 'code' and 'safe'
	let script = code

	if (!script.includes("function init(")) {
		script = "function init() {\n" + script + "\n}"
	}

	if (system.forceSystemLog) {
		for (const i in csw.functions) {
			script = script.replaceAll(csw.functions[i] + "(", csw.functions[i] + "(token,")
		}
	}

	return script
}

function init(args) {
	if (args[0] == undefined) {
		return
	}

	const dir = csw.fs.toDirectory(args[0], parent.dir)

	csw.processes.execute(PID, dir, [], system !== undefined)
}