#! /usr/bin/node

async function init(args) {
    const cmd = args.join(" ")

    if (cmd == undefined) return

    local.shared = parent

    const password = await parent.getInput("Password:", false)
    std.out = "Password:"
    await call.chusr("root", password)

    await local.shared.run(cmd, true)
}